ALL = allmajors1 allmajors2 allmajors4 biggen histomap1 \
        histomap2 histomap3 histovector simpgolf tiger_and_jack allmajors3 

all: $(ALL)

clean: 
	rm -f *.o $(ALL)

allmajors1: allmajors1.o
	g++ -o allmajors1 -O allmajors1.o

allmajors2: allmajors2.o
	g++ -o allmajors2 -O allmajors2.o

allmajors3: allmajors3.o
	g++ -o allmajors3 -O allmajors3.o

allmajors4: allmajors4.o
	g++ -o allmajors4 -O allmajors4.o

biggen: biggen.o
	g++ -o biggen -O biggen.o

histomap1: histomap1.o
	g++ -o histomap1 -O histomap1.o

histomap2: histomap2.o
	g++ -o histomap2 -O histomap2.o

histomap3: histomap3.o
	g++ -o histomap3 -O histomap3.o

histovector: histovector.o
	g++ -o histovector -O histovector.o

simpgolf: simpgolf.o
	g++ -o simpgolf -O simpgolf.o

tiger_and_jack: tiger_and_jack.o
	g++ -o tiger_and_jack -O tiger_and_jack.o
